const Data = [
  {
    id: 1,
    Title: "life lesson with kate",
    price: 136,
    imgs: "katie-zaferes.png",
    rating: 5.0,
    reivewCount: 6,
    location: "Eritrea",
    openSpot: 0,
  },
  {
    id: 2,
    Title: "Lerning wedding photography",
    price: 125,
    imgs: "wedding-photography.png",
    rating: 4.8,
    reivewCount: 30,
    location: "online",
    openSpot: 27,
  },
  {
    id: 3,
    Title: "Group mountain Biking",
    price: 50,
    imgs: "katie-zaferes.png",
    rating: 4.8,
    reivewCount: 2,
    location: "Norway",
    openSpot: 3,
  },
  {
    id: 4,
    Title: "Group mountain Biking",
    price: 50,
    imgs: "mountain-bike.png",
    rating: 4.8,
    reivewCount: 2,
    location: "Norway",
    openSpot: 3,
  },
];
export default Data;
